// Ownership-scoped data access (Phase 7F, D24). Every function runs inside withActorTransaction() and derives WHO is asking and
// WHICH customer they own from the verified actor session in PostgreSQL - never from an argument. Customer scoping is a SQL
// predicate (`customer_id = <actor's customer>`), not a post-fetch check; the same rule is enforced again by row-level security.
//
// "Not yours" and "does not exist" are the same answer: `null` (the route turns it into 404). Malformed ids are also `null`.
// A customer login without a valid customer link never means "all customers": it fails closed.
import type { Queryable } from "./client";
import { authorize, getActorContext, isAllowed, type ActorContext, type Operation } from "./authz";
import { recordAudit } from "./audit";
import { DomainError } from "./errors";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const isUuid = (v: unknown): v is string => typeof v === "string" && UUID.test(v);

/** NULL = unrestricted (staff / admin for operations they hold); otherwise the one customer the actor owns. */
async function scope(tx: Queryable, any: Operation, own: Operation): Promise<{ ctx: ActorContext; customerId: string | null }> {
  const ctx = await getActorContext(tx);
  if (isAllowed(ctx, any)) return { ctx, customerId: null };
  if (isAllowed(ctx, own) && ctx.customerId) return { ctx, customerId: ctx.customerId };
  throw new DomainError("NOT_AUTHORIZED", "You are not allowed to perform this operation");
}

// ------------------------------------------------------------------ customers
export async function getCustomer(tx: Queryable, id: string) {
  const { ctx } = await scope(tx, "customer.read.any", "customer.update_self");
  if (!isUuid(id)) return null;
  const { rows } = await tx.query(
    `SELECT id, name, phone, email, shipping_mark, shipping_address, package_tier, preferred_warehouse_id, notes, status
       FROM customers WHERE id = $1 AND ($2::uuid IS NULL OR id = $2)`,
    [id, ctx.role === "customer" ? ctx.customerId : null]);
  return rows[0] ?? null;
}

/** The ONLY customer write: address and notes of the actor's own record. Unknown keys are rejected, never ignored. */
export async function updateCustomerSelf(tx: Queryable, patch: { shippingAddress?: string | null; notes?: string | null }) {
  const ctx = await authorize(tx, "customer.update_self");
  const allowed = new Set(["shippingAddress", "notes"]);
  const extra = Object.keys(patch ?? {}).filter((k) => !allowed.has(k));
  if (extra.length) throw new DomainError("INVALID_INPUT", `Customers may change only their address and notes (not: ${extra.join(", ")})`);
  if (patch.shippingAddress === undefined && patch.notes === undefined) throw new DomainError("INVALID_INPUT", "Nothing to update");
  for (const [k, v] of Object.entries(patch)) if (v != null && (typeof v !== "string" || v.length > 2000)) throw new DomainError("INVALID_INPUT", `${k} is invalid`);
  const { rows } = await tx.query(
    `UPDATE customers SET shipping_address = CASE WHEN $2::boolean THEN $3 ELSE shipping_address END,
                          notes = CASE WHEN $4::boolean THEN $5 ELSE notes END
      WHERE id = $1 RETURNING id, shipping_address, notes`,
    [ctx.customerId, patch.shippingAddress !== undefined, patch.shippingAddress ?? null, patch.notes !== undefined, patch.notes ?? null]);
  if (!rows[0]) throw new DomainError("NOT_FOUND", "Customer not found");
  await recordAudit(tx, { action: "customer.update_self", entityType: "customer", entityId: rows[0].id, after: { fields: Object.keys(patch) } });
  return rows[0];
}

/** Customer identity / configuration: super_admin only. Allow-list; the shipping mark is regenerated by a later workflow, not edited. */
export async function updateCustomerAdmin(tx: Queryable, id: string, patch: Record<string, unknown>) {
  await authorize(tx, "customer.admin");
  if (!isUuid(id)) throw new DomainError("NOT_FOUND", "Customer not found");
  const cols: Record<string, string> = {
    name: "name", phone: "phone", email: "email", shippingAddress: "shipping_address", notes: "notes",
    packageTier: "package_tier", preferredWarehouseId: "preferred_warehouse_id", status: "status",
  };
  const keys = Object.keys(patch);
  const bad = keys.filter((k) => !Object.hasOwn(cols, k));
  if (bad.length) throw new DomainError("INVALID_INPUT", `Fields not editable here: ${bad.join(", ")}`);
  if (!keys.length) throw new DomainError("INVALID_INPUT", "Nothing to update");
  const set = keys.map((k, i) => `${cols[k]} = $${i + 2}`).join(", ");
  const { rows } = await tx.query(`UPDATE customers SET ${set} WHERE id = $1 RETURNING id`, [id, ...keys.map((k) => patch[k])]);
  if (!rows[0]) throw new DomainError("NOT_FOUND", "Customer not found");
  await recordAudit(tx, { action: "customer.update", entityType: "customer", entityId: id, after: { fields: keys } });
  return rows[0];
}

// ------------------------------------------------------------------ items / cartons
export async function getItem(tx: Queryable, id: string) {
  const { customerId } = await scope(tx, "item.read.any", "item.read.own");
  if (!isUuid(id)) return null;
  return (await tx.query(`SELECT * FROM items WHERE id = $1 AND archived_at IS NULL AND ($2::uuid IS NULL OR customer_id = $2)`, [id, customerId])).rows[0] ?? null;
}
export async function getItemByRef(tx: Queryable, itemRef: string) {
  const { customerId } = await scope(tx, "item.read.any", "item.read.own");
  return (await tx.query(`SELECT * FROM items WHERE item_ref = $1 AND archived_at IS NULL AND ($2::uuid IS NULL OR customer_id = $2)`, [String(itemRef), customerId])).rows[0] ?? null;
}
/** `filter.customerId` narrows staff queries only; for a customer it is ignored (the actor's own customer is used). */
export async function listItems(tx: Queryable, filter: { customerId?: string; status?: string; limit?: number; offset?: number } = {}) {
  const { customerId } = await scope(tx, "item.read.any", "item.read.own");
  const cid = customerId ?? (filter.customerId && isUuid(filter.customerId) ? filter.customerId : null);
  if (customerId === null && filter.customerId && !cid) return [];
  const limit = Math.min(Math.max(Number(filter.limit) || 50, 1), 500), offset = Math.max(Number(filter.offset) || 0, 0);
  return (await tx.query(
    `SELECT * FROM items WHERE archived_at IS NULL AND ($1::uuid IS NULL OR customer_id = $1) AND ($2::text IS NULL OR status = $2)
      ORDER BY created_at DESC, id LIMIT $3 OFFSET $4`, [cid, filter.status ?? null, limit, offset])).rows;
}
export async function getItemHistory(tx: Queryable, itemId: string) {
  const { customerId } = await scope(tx, "item.read.any", "item.read.own");
  if (!isUuid(itemId)) return null;
  const owned = (await tx.query(`SELECT 1 FROM items WHERE id = $1 AND ($2::uuid IS NULL OR customer_id = $2)`, [itemId, customerId])).rows[0];
  if (!owned) return null;                       // same answer as "no such item"
  return (await tx.query(`SELECT old_status, new_status, reason, occurred_at FROM status_events WHERE entity_type = 'item' AND entity_id = $1 ORDER BY id`, [itemId])).rows;
}
export async function getCarton(tx: Queryable, id: string) {
  const { customerId } = await scope(tx, "carton.read.any", "carton.read.own");
  if (!isUuid(id)) return null;
  return (await tx.query(`SELECT * FROM cartons WHERE id = $1 AND ($2::uuid IS NULL OR customer_id = $2)`, [id, customerId])).rows[0] ?? null;
}
export async function listCartons(tx: Queryable, filter: { customerId?: string; limit?: number } = {}) {
  const { customerId } = await scope(tx, "carton.read.any", "carton.read.own");
  const cid = customerId ?? (filter.customerId && isUuid(filter.customerId) ? filter.customerId : null);
  if (customerId === null && filter.customerId && !cid) return [];
  return (await tx.query(`SELECT * FROM cartons WHERE ($1::uuid IS NULL OR customer_id = $1) ORDER BY created_at DESC, id LIMIT $2`, [cid, Math.min(Math.max(Number(filter.limit) || 50, 1), 500)])).rows;
}

// ------------------------------------------------------------------ invoices / payments (staff have no financial read access)
export async function getInvoice(tx: Queryable, id: string) {
  const { customerId } = await scope(tx, "invoice.read.any", "invoice.read.own");
  if (!isUuid(id)) return null;
  const inv = (await tx.query(`SELECT * FROM invoices WHERE id = $1 AND ($2::uuid IS NULL OR customer_id = $2)`, [id, customerId])).rows[0];
  if (!inv) return null;
  const lines = (await tx.query(`SELECT * FROM invoice_lines WHERE invoice_id = $1 ORDER BY line_no`, [id])).rows;
  return { ...inv, lines };
}
export async function listInvoices(tx: Queryable, filter: { customerId?: string; limit?: number } = {}) {
  const { customerId } = await scope(tx, "invoice.read.any", "invoice.read.own");
  const cid = customerId ?? (filter.customerId && isUuid(filter.customerId) ? filter.customerId : null);
  if (customerId === null && filter.customerId && !cid) return [];
  return (await tx.query(`SELECT * FROM invoices WHERE ($1::uuid IS NULL OR customer_id = $1) ORDER BY created_at DESC, id LIMIT $2`, [cid, Math.min(Math.max(Number(filter.limit) || 50, 1), 500)])).rows;
}
export async function getInvoicePayments(tx: Queryable, invoiceId: string) {
  const { customerId } = await scope(tx, "invoice.read.any", "invoice.read.own");
  if (!isUuid(invoiceId)) return null;
  const owned = (await tx.query(`SELECT 1 FROM invoices WHERE id = $1 AND ($2::uuid IS NULL OR customer_id = $2)`, [invoiceId, customerId])).rows[0];
  if (!owned) return null;
  return (await tx.query(`SELECT id, amount_ghs, status, method, source, created_at, voided_at FROM payments WHERE invoice_id = $1 ORDER BY created_at, id`, [invoiceId])).rows;
}
