name = "movezz-shipping"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat_v2"]

pages_build_output_dir = ".pages-deploy"

[vars]
NODE_ENV = "production"

# Cloudflare Pages GitHub CI build settings
# Build command:  npm install && npm run ci:build
# Build output:   .pages-deploy
# Node version:   18 (or 20)
