// Core logic for scripts/bootstrap-admin.mjs - the ONLY supported way to create the first super_admin.
//
// Design rules (Phase 5):
//  * no credential is stored in source, generated by the script, or printed anywhere;
//  * the operator supplies the password through a hidden prompt or --password-stdin;
//  * nothing happens without explicit confirmation of the exact e-mail address;
//  * the script refuses to run when a super_admin already exists (unless --allow-additional);
//  * the operation is recorded in the ActivityLogs table.
//
// Everything that touches the network goes through the injected `fetchImpl`, so the logic is unit-testable.

export const MIN_PASSWORD_LENGTH = 12;
const AIRTABLE = "https://api.airtable.com/v0";
const IDENTITY = "https://identitytoolkit.googleapis.com/v1/accounts";

const COMMON = new Set(["password", "passw0rd", "123456789012", "qwertyuiopas", "administrator", "letmein12345", "welcome12345", "movezz", "de-movezz"]);

export class BootstrapError extends Error {
  constructor(message, code = 1) {
    super(message);
    this.name = "BootstrapError";
    this.exitCode = code;
  }
}

/** Parses CLI flags. The password is deliberately NOT accepted as a flag (it would leak into shell history and `ps`). */
export function parseArgs(argv) {
  const opts = { email: "", confirm: "", dryRun: false, allowAdditional: false, passwordStdin: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const take = () => {
      const v = argv[++i];
      if (v === undefined || v.startsWith("--")) throw new BootstrapError(`${a} needs a value`);
      return v;
    };
    if (a === "--email") opts.email = take().trim().toLowerCase();
    else if (a === "--confirm") opts.confirm = take().trim().toLowerCase();
    else if (a === "--dry-run") opts.dryRun = true;
    else if (a === "--allow-additional") opts.allowAdditional = true;
    else if (a === "--password-stdin") opts.passwordStdin = true;
    else if (a === "--password" || a.startsWith("--password=")) {
      throw new BootstrapError("Refusing --password: a password on the command line leaks into shell history and process listings. Use the hidden prompt or --password-stdin.");
    } else throw new BootstrapError(`Unknown argument: ${a}`);
  }
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(opts.email)) throw new BootstrapError("--email <address> is required and must be a valid e-mail address");
  return opts;
}

/** Returns a list of problems (empty = acceptable). Never includes the password itself in a message. */
export function passwordProblems(password, email) {
  const problems = [];
  if (typeof password !== "string" || password.length < MIN_PASSWORD_LENGTH) problems.push(`must be at least ${MIN_PASSWORD_LENGTH} characters`);
  if (password && password.length > 128) problems.push("must be at most 128 characters");
  if (password && /^(.)\1+$/.test(password)) problems.push("must not be one repeated character");
  if (password && /^\d+$/.test(password)) problems.push("must not be digits only");
  if (password && COMMON.has(password.toLowerCase())) problems.push("is too common");
  const local = (email || "").split("@")[0];
  if (password && local.length >= 3 && password.toLowerCase().includes(local)) problems.push("must not contain the e-mail name");
  return problems;
}

function requireEnv(env) {
  const need = ["NEXT_PUBLIC_FIREBASE_API_KEY", "AIRTABLE_API_KEY", "AIRTABLE_BASE_ID"];
  const missing = need.filter((k) => !env[k]);
  if (missing.length) throw new BootstrapError(`Missing environment variables: ${missing.join(", ")}`);
  return { firebaseKey: env.NEXT_PUBLIC_FIREBASE_API_KEY, atKey: env.AIRTABLE_API_KEY, base: env.AIRTABLE_BASE_ID };
}

async function json(res) {
  try {
    return await res.json();
  } catch {
    return {};
  }
}

const maskBase = (id) => `${String(id).slice(0, 3)}…${String(id).slice(-4)}`;

/**
 * Runs the bootstrap. `io` provides: log(msg), getPassword(), confirm(promptText) -> string.
 * Returns a summary object that never contains the password.
 */
export async function bootstrapAdmin({ opts, env, fetchImpl, io, operator = "unknown", now = () => new Date() }) {
  const { firebaseKey, atKey, base } = requireEnv(env);
  const atHeaders = { Authorization: `Bearer ${atKey}`, "Content-Type": "application/json" };

  // 1. Refuse to act when an admin already exists.
  const q = encodeURIComponent("{Role} = 'super_admin'");
  const existingRes = await fetchImpl(`${AIRTABLE}/${base}/Users?filterByFormula=${q}&maxRecords=1`, { headers: atHeaders });
  const existing = await json(existingRes);
  if (!existingRes.ok) throw new BootstrapError(`Could not read the Users table (HTTP ${existingRes.status}). Nothing was changed.`, 2);
  const adminExists = Array.isArray(existing.records) && existing.records.length > 0;
  if (adminExists && !opts.allowAdditional) {
    throw new BootstrapError("A super_admin already exists. Bootstrap is only for the FIRST administrator. Use the application's staff management, or pass --allow-additional if you really mean to create another one.", 3);
  }

  io.log(`Target Airtable base: ${maskBase(base)}`);
  io.log(`Will create a super_admin for: ${opts.email}`);
  if (opts.dryRun) {
    io.log("Dry run: no changes were made.");
    return { dryRun: true, adminAlreadyExisted: adminExists };
  }

  // 2. Explicit confirmation of the exact address (flag for automation, typed answer for humans).
  const confirmation = opts.confirm || (await io.confirm(`Type the e-mail address again to confirm creating a super_admin (${opts.email}): `));
  if (String(confirmation).trim().toLowerCase() !== opts.email) throw new BootstrapError("Confirmation did not match. Nothing was changed.", 4);

  // 3. The operator supplies the password; it is validated but never logged.
  const password = await io.getPassword();
  const problems = passwordProblems(password, opts.email);
  if (problems.length) throw new BootstrapError(`Password rejected: ${problems.join("; ")}. Nothing was changed.`, 5);

  // 4. Create (or authenticate) the Firebase login.
  let uid;
  const create = await fetchImpl(`${IDENTITY}:signUp?key=${firebaseKey}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ email: opts.email, password, returnSecureToken: false }),
  });
  const created = await json(create);
  if (create.ok) {
    uid = created.localId;
    io.log("Firebase login created.");
  } else if (String(created?.error?.message ?? "").includes("EMAIL_EXISTS")) {
    // The operator must prove they control the existing login with the password they just typed.
    const signIn = await fetchImpl(`${IDENTITY}:signInWithPassword?key=${firebaseKey}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ email: opts.email, password, returnSecureToken: true }),
    });
    const signed = await json(signIn);
    if (!signIn.ok) throw new BootstrapError(`This e-mail already has a Firebase login and the password you entered does not match it (${signed?.error?.message ?? "sign-in failed"}). Nothing was changed.`, 6);
    uid = signed.localId;
    io.log("Existing Firebase login verified.");
  } else {
    throw new BootstrapError(`Firebase error: ${created?.error?.message ?? `HTTP ${create.status}`}. Nothing was changed.`, 7);
  }
  if (!uid) throw new BootstrapError("Firebase did not return a user id. Nothing was changed.", 7);

  // 5. Create the application user.
  const userRes = await fetchImpl(`${AIRTABLE}/${base}/Users`, {
    method: "POST",
    headers: atHeaders,
    body: JSON.stringify({ fields: { FirebaseUID: uid, Email: opts.email, Role: "super_admin", LastLogin: now().toISOString() } }),
  });
  const user = await json(userRes);
  if (!userRes.ok) throw new BootstrapError(`Could not create the Users record (${user?.error?.message ?? `HTTP ${userRes.status}`}). The Firebase login exists; re-run to finish.`, 8);

  // 6. Audit trail (no secrets).
  const audit = await fetchImpl(`${AIRTABLE}/${base}/ActivityLogs`, {
    method: "POST",
    headers: atHeaders,
    body: JSON.stringify({
      fields: {
        Action: "BOOTSTRAP_SUPER_ADMIN",
        UserEmail: opts.email,
        UserRole: "super_admin",
        Details: `Created via scripts/bootstrap-admin.mjs by operator ${operator}. firebaseUid=${uid}; usersRecord=${user.id}; additionalAdmin=${adminExists}`,
        EntityType: "User",
        EntityID: user.id,
        Timestamp: now().toISOString(),
      },
    }),
  });
  if (!audit.ok) {
    throw new BootstrapError(`The super_admin WAS created (Users record ${user.id}) but the audit record could not be written (HTTP ${audit.status}). Record this operation manually.`, 9);
  }

  io.log(`Super admin created: ${opts.email} (Users record ${user.id}). Audit record written.`);
  io.log("Sign in with the password you just entered. It was not stored or displayed.");
  return { dryRun: false, uid, usersRecordId: user.id, additionalAdmin: adminExists };
}
